/* eslint-disable */
// Section 3 — Financial Modeling
// P1 Smart Invoice: faithful viewer of the canonical Excel workbook
// (models/Mal_P1_SmartInvoice.xlsx · 18 sheets). Reads window.MAL_P1_DATA
// (auto-generated by models/sync_p1_to_jsx.py — never edit by hand).
// P2/P3/P4: locked "in progress" cards.
//
// Excel is the single source of truth. JSX never recomputes the model.

const { useState: fS, useMemo: fM, useCallback: fCB } = React;

// ============================================================
// Formatting helpers
// ============================================================
const aedM = (n, dp = 1) => 'AED ' + (Number.isFinite(n) ? n.toFixed(dp) : '0') + 'M';
const aedB = (n, dp = 2) => 'AED ' + (Number.isFinite(n) ? (n / 1000).toFixed(dp) : '0') + 'B';
const pct  = (n, dp = 1) => (Number.isFinite(n) ? n.toFixed(dp) : '0') + '%';
const ratio = (n, dp = 2) => (Number.isFinite(n) ? n.toFixed(dp) : '0') + 'x';

function aedSmart(n) {
  if (!Number.isFinite(n)) return 'AED 0';
  if (Math.abs(n) >= 1000) return aedB(n, 2);
  return aedM(n, 1);
}

// ============================================================
// Product catalogue with status
// ============================================================
const FIN_PRODUCTS = [
  { id: 'p1', code: 'Product 1', title: 'Smart Invoice + Term Extension',
    blurb: 'Invoice discount + BNPL (60-180d) + 6-mo Term Extension · UAE-validated · 5-yr horizon',
    color: 'lilac', status: 'live' },
  { id: 'p2', code: 'Product 2', title: 'Healthcare Receivables Engine',
    blurb: 'Same-day claim advance · multi-payer · predictive adjudication',
    color: 'coral', status: 'in-progress' },
  { id: 'p3', code: 'Product 3', title: 'Anchor-Led Supply Chain Finance',
    blurb: 'Reverse factoring · daily dynamic-discount auction',
    color: 'ink', status: 'in-progress' },
  { id: 'p4', code: 'Product 4', title: 'EDB-Guaranteed Distribution + FLDG',
    blurb: 'Pathway B · partner-bank co-lending with First Loss Default Guarantee',
    color: 'peach', status: 'in-progress' },
];

const SCENARIOS = [
  { key: 'base',     label: 'Base',     tone: 'iri'    },
  { key: 'upside',   label: 'Upside',   tone: 'success' },
  { key: 'downside', label: 'Downside', tone: 'warn'   },
  { key: 'stress',   label: 'Stress',   tone: 'danger' },
];

// ============================================================
// Section root
// ============================================================
function SectionFinancial({ lang, isMobile }) {
  const flagshipId = 'p1-smart-invoice';
  const [activeProductId, setActiveProductId] = fS(flagshipId);
  const [tourOpen, setTourOpen] = fS(false);
  const isAr = lang === 'ar';
  const data = window.MAL_P1_DATA;
  const catalogue = window.MAL_PRODUCT_CATALOGUE || [];
  const product = window.MAL_PRODUCT_BY_ID?.[activeProductId];

  if (!data) {
    return (
      <div className="mal-section-page" style={{ padding: 60, textAlign: 'center' }}>
        <h1 style={{ fontFamily: 'var(--mal-font-display)', fontStyle: 'italic' }}>Economics</h1>
        <p style={{ color: 'var(--mal-mid)' }}>
          Model data not loaded. Run <code>.venv-models/bin/python models/sync_p1_to_jsx.py</code> to regenerate.
        </p>
      </div>
    );
  }

  const isLive = product?.status === 'live';
  const Tour = window.MalTour;
  const TourBtn = window.MalTourButton;
  const tourSteps = isLive ? buildEconomicsTourSteps(data, isAr) : [];

  return (
    <div className="mal-section-page" dir={isAr ? 'rtl' : 'ltr'}>
      {/* Top row: dropdown + Excel download (left) · tour button (right) */}
      <div style={{
        display: 'flex', justifyContent: 'space-between',
        alignItems: 'center', gap: 16, flexWrap: 'wrap',
        marginBottom: 22,
      }}>
        <div data-tour-id="econ-selector" style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
          <FinGroupedProductSelector
            catalogue={catalogue}
            productId={activeProductId}
            onPickProduct={setActiveProductId}
            isAr={isAr} isMobile={isMobile}/>
          {isLive && (
            <a href={`models/${data.meta.workbook}`} download={data.meta.workbook}
               title={`${data.meta.workbook} · ${data.meta.sheets} sheets · synced ${data.meta.lastUpdated}`}
               className="mal-excel-cta"
               style={{
                 display: 'inline-flex', alignItems: 'center', gap: 8,
                 padding: '9px 16px', borderRadius: 999,
                 background: '#107C41',
                 border: '1px solid #0E6939',
                 color: '#FFFFFF',
                 fontSize: 12.5, fontWeight: 600, letterSpacing: '0.01em',
                 textDecoration: 'none',
                 transition: 'background .15s, transform .15s',
               }}
               onMouseEnter={(e) => {
                 e.currentTarget.style.background = '#0E6939';
                 e.currentTarget.style.transform = 'translateY(-1px)';
               }}
               onMouseLeave={(e) => {
                 e.currentTarget.style.background = '#107C41';
                 e.currentTarget.style.transform = 'translateY(0)';
               }}>
              <DownloadArrowIcon/>
              <ExcelIcon/>
              <span>{isAr ? 'تحميل إكسل' : 'Download Excel'}</span>
            </a>
          )}
        </div>
        {TourBtn && isLive && (
          <TourBtn lang={lang} onStart={() => setTourOpen(true)}/>
        )}
      </div>

      {isLive && <P1Workbench data={data} isMobile={isMobile} isAr={isAr}/>}
      {!isLive && product && <InProgressCard product={product} isAr={isAr}/>}

      {Tour && tourOpen && (
        <Tour steps={tourSteps} onClose={() => setTourOpen(false)} isOpen={tourOpen} lang={lang}/>
      )}
    </div>
  );
}

// ============================================================
// Tour steps for the Economics section
// ============================================================
function buildEconomicsTourSteps(data, isAr) {
  const r3 = data.ratios.y3, fy = data.fiveYearSummary;
  return [
    { title: isAr ? 'مرحباً بك في الاقتصاد' : 'Welcome to Economics',
      body: [
        isAr
          ? 'هذه هي الجولة الكاملة للنموذج المالي لمنتج "الفاتورة الذكية".'
          : 'This is the complete walkthrough of the canonical 5-year financial model for the Smart Invoice product.',
        isAr
          ? `المصدر: ${data.meta.workbook} · ١٨ ورقة في إكسل · جميع الأرقام مزامنة من هناك.`
          : `Source: ${data.meta.workbook} · 18 Excel sheets · every number on screen is auto-synced from there.`,
        isAr
          ? `بعد الانتهاء، ستفهم الافتراضات وراء العائد على الأصول ${r3.roaPct.toFixed(2)}٪، والمخاطر، والتمويل، ورأس المال.`
          : `By the end you'll understand every assumption behind ROA ${r3.roaPct.toFixed(2)}%, risk, funding and capital.`,
      ],
      position: 'center', selector: null },

    { title: isAr ? 'كتالوج المنتجات' : 'Product catalogue',
      body: isAr
        ? '٢١ منتجاً مجمعة في ٦ فئات. الفاتورة الذكية فقط مفعلة. اضغط الأخرى لرؤية التعريف ومرحلة التنفيذ.'
        : 'All 21 products grouped into 6 categories. Only Smart Invoice is active. Clicking any other product shows its blurb and "in progress" status.',
      selector: '[data-tour-id="econ-selector"]' },

    { title: isAr ? 'مصدر الحقيقة' : 'Source of truth',
      body: isAr
        ? 'كل الأرقام في هذه الصفحة تأتي من ورقة إكسل واحدة. للتعديل، حرر إكسل ثم شغّل sync_p1_to_jsx.py.'
        : 'All numbers come from a single Excel workbook. To change anything, edit Excel then run sync_p1_to_jsx.py — the prototype is a viewer, not a duplicate model.',
      selector: '[data-tour-id="econ-source"]' },

    { title: isAr ? 'مؤشرات الأداء الرئيسية' : 'Hero KPIs',
      body: [
        isAr
          ? `صرف الـ٥ سنوات: ${(fy.face/1000).toFixed(1)}B درهم. مساهمة صافية تراكمية: ${fy.cumNetContrib.toFixed(0)}M.`
          : `5-yr disbursement: AED ${(fy.face/1000).toFixed(1)}B. Cumulative net contribution: AED ${fy.cumNetContrib.toFixed(0)}M.`,
        isAr
          ? `العائد على الأصول Y3: ${r3.roaPct.toFixed(2)}٪. RAROC: ${r3.rarocPct.toFixed(0)}٪. حقوق ملكية مرفوعة: ${(fy.totalEquityRaised).toFixed(0)}M.`
          : `Y3 ROA: ${r3.roaPct.toFixed(2)}%. RAROC: ${r3.rarocPct.toFixed(0)}%. Equity raised: AED ${fy.totalEquityRaised.toFixed(0)}M.`,
      ],
      selector: '[data-tour-id="econ-hero"]' },

    { title: isAr ? 'لوحة الروافع' : 'The lever panel',
      body: isAr
        ? '٣١ رافعة منظمة في ٨ مجموعات. للقراءة فقط لأن إكسل مصدر الحقيقة. الرافعات الحارة محددة بنقطة بنفسجية.'
        : '31 input levers organised into 8 collapsible groups. Read-only here since Excel is the canonical source. Critical groups have a lilac dot.',
      selector: '[data-tour-id="econ-levers"]' },

    { title: isAr ? 'التسعير والرسوم' : 'Pricing & fees · the value lever',
      body: [
        isAr
          ? 'هذه الرافعة تحرّك الإيرادات مباشرة. كل تحريك ٣٠ نقطة يغير العائد بـ ١-٢ نقطة كاملة.'
          : 'These directly drive revenue. A 30 bps move on the Pay-30 fee shifts ROA by 1–2 full points.',
        isAr
          ? `Pay-30 ${data.inputs.fee_pay30_mo}٪/شهر · BNPL ${data.inputs.fee_bnpl_mo}٪/شهر · تمديد ${data.inputs.fee_ext_apr}٪ APR.`
          : `Pay-30 ${data.inputs.fee_pay30_mo}%/mo · BNPL ${data.inputs.fee_bnpl_mo}%/mo · Extension ${data.inputs.fee_ext_apr}% APR.`,
      ],
      selector: '[data-tour-id="econ-levers-pricing"]' },

    { title: isAr ? 'PD/LGD/EAD · إطار Basel' : 'Risk · PD / LGD / EAD',
      body: [
        isAr
          ? 'إطار Basel III IRB لكل مسار: احتمال التعثر، نسبة الخسارة، والتعرض. الخسارة المرتقبة = PD × LGD × EAD.'
          : 'Basel III IRB framework per track: probability of default, loss given default, exposure at default. Expected loss = PD × LGD × EAD.',
        isAr
          ? `Pay-30: PD ${data.risk.pay30.pd}٪، LGD ${data.risk.pay30.lgd}٪. BNPL: PD ${data.risk.bnpl.pd}٪، LGD ${data.risk.bnpl.lgd}٪. تمديد: PD ${data.risk.ext.pd}٪، LGD ${data.risk.ext.lgd}٪.`
          : `Pay-30: PD ${data.risk.pay30.pd}% · LGD ${data.risk.pay30.lgd}%. BNPL: PD ${data.risk.bnpl.pd}% · LGD ${data.risk.bnpl.lgd}%. Extension: PD ${data.risk.ext.pd}% · LGD ${data.risk.ext.lgd}%.`,
      ],
      selector: '[data-tour-id="econ-levers-risk"]' },

    { title: isAr ? 'لوحة السيناريوهات' : 'Scenario picker',
      body: isAr
        ? 'أربعة سيناريوهات محسوبة مسبقاً في إكسل: Base / Upside / Downside / Stress. اضغط أي زر للتحديث الفوري.'
        : 'Four scenarios pre-computed in Excel: Base / Upside / Downside / Stress. Click any to switch — Y3 KPIs update instantly with deltas vs Base.',
      selector: '[data-tour-id="econ-scenarios"]' },

    { title: isAr ? 'خطة الصرف ٥ سنوات' : 'Disbursement plan · Y1 → Y5',
      body: isAr
        ? `الصرف يقفز من ٢٥٠M في السنة الأولى إلى ١٣B في السنة الخامسة (نمو مركّب ١٧٠٪). تكوين الكتاب: BNPL يحمل ٦٤٪.`
        : `Face-value disbursement grows from AED 250M Y1 to AED 13B Y5 — 170% CAGR. The book composition shows BNPL carries 64% (105-day tenor is heavy).`,
      selector: '[data-tour-id="econ-disb"]' },

    { title: isAr ? 'تدرج الهامش (Y3)' : 'Margin walk · Y3',
      body: isAr
        ? 'من العائد الإجمالي (١٧.٢٪) إلى الصافي (٥.٧٪). كل عمود يطرح طبقة: تكلفة التمويل، الخسائر، التشغيل.'
        : 'From gross yield (17.2%) down to net contribution (5.7%). Each bar subtracts a layer: cost of funds, expected loss, operating expense.',
      selector: '[data-tour-id="econ-margin"]' },

    { title: isAr ? 'بيان الربح والخسارة' : '5-year P&L table',
      body: isAr
        ? 'البيان السنوي الكامل بالمليون درهم. لاحظ نمو NIM من ٧M إلى ٣٥٨M، وOpEx ينخفض كنسبة من الكتاب.'
        : 'Full annual P&L in AED M. Watch NIM grow from 7M to 358M, while OpEx drops as a % of book (operating leverage).',
      selector: '[data-tour-id="econ-pnl-table"]' },

    { title: isAr ? 'طبقة المخاطر التفصيلية' : 'Risk layer · detail',
      body: isAr
        ? 'إجهاد ١.٥× يحرّك الخسارة المرجحة من ٢.٦٪ إلى ٤.٠٪ من الكتاب — لا تزال مغطاة بهامش الفائدة.'
        : '1.5× CBUAE-style stress moves the weighted expected loss from 2.6% to 4.0% of book — still covered by NIM. This is the regulator-friendly framing.',
      selector: '[data-tour-id="econ-risk-card"]' },

    { title: isAr ? 'خطة رأس المال' : 'Capital plan · Tier-1 trajectory',
      body: isAr
        ? `جولات: بذرة + سلسلة A (Y1: 110M)، B (Y2: 250M)، C (Y4: 500M). نسبة Tier-1 تظل أعلى من ١٣٪ في كل سنة.`
        : `Equity raise schedule: Seed + Series A (Y1: 110M), Series B (Y2: 250M), Series C (Y4: 500M). Tier-1 ratio stays above the CBUAE 13% threshold every year.`,
      selector: '[data-tour-id="econ-capital"]' },

    { title: isAr ? 'هيكل التمويل' : 'Funding stack',
      body: isAr
        ? 'تكلفة التمويل المرجحة ٦.٩٨٪ مقابل الافتراض ٦.٥٪ — فجوة ٤٨ نقطة (مقبولة). كل العهود تجتاز الفحص.'
        : 'Blended COF 6.98% vs the 6.5% assumption — a 49 bps gap (within tolerance). Senior 78% / Mezz 10% / Equity 12%. All covenants PASS.',
      selector: '[data-tour-id="econ-funding"]' },

    { title: isAr ? 'الاقتصاد لكل ١٠٠ ألف' : 'Unit economics · per AED 100k',
      body: isAr
        ? 'مساهمة لكل فاتورة بحسب المسار. هذا ما تحمله للجنة التسعير عند نقاش رفع الرسوم أو خفض LGD.'
        : 'Per-invoice contribution by track. This is what you take to the pricing committee when debating fee uplift or LGD-floor.',
      selector: '[data-tour-id="econ-unit-econ"]' },

    { title: isAr ? 'دفعات العمر · Vintage' : 'Vintage cohorts · loss timing',
      body: isAr
        ? 'منحنى الخسارة التراكمية لكل دفعة سنوية. ٣٠٪ من الخسارة في M0–6، ٥٠٪ M7–18، ٢٠٪ M19–24.'
        : 'Cumulative loss curve per annual cohort. Lognormal: 30% in months 0–6, 50% in 7–18, 20% in 19–24. Lifetime loss settles at 0.60% of advanced principal.',
      selector: '[data-tour-id="econ-vintage"]' },

    { title: isAr ? 'مقارنة السيناريوهات' : 'Scenario comparison · Y3',
      body: isAr
        ? 'الأربعة جنباً إلى جنب. حتى السيناريو المضغوط يحقق ROA ٣.٨٨٪ — فوق عتبة CBUAE.'
        : 'All four side-by-side. Even Stress prints ROA 3.88% — above the CBUAE NBFC threshold. Stress moves PDs +80%, COF +200 bps, OpEx +50 bps.',
      selector: '[data-tour-id="econ-scen-compare"]' },

    { title: isAr ? 'تحليل التعادل' : 'Break-even readout',
      body: isAr
        ? 'تعادل صرف Y2 عند ٤٩٨M (مقابل ١٫٥B مخطط — هامش ٢٠١٪). PDs يمكن أن ترتفع ١٣٢٪ قبل أن يصل ROA إلى ٥٪.'
        : 'Y2 break-even disbursement: AED 498M (vs 1.5B plan — 201% headroom). PDs can rise 132% before Y3 ROA falls to 5%. Tolerates Stress.',
      selector: '[data-tour-id="econ-breakeven"]' },

    { title: isAr ? 'حساسية المخاطر × التمويل' : 'Sensitivity · PD × COF',
      body: isAr
        ? 'مصفوفة ٧×٦ تظهر مساهمة Y3 الصافية تحت ضغط مزدوج. الخلية الوسطى هي الحالة الأساسية.'
        : 'A 7×6 grid showing Y3 net contribution under joint COF and default-multiplier shocks. Centre cell is the base case; red = pain, green = gain.',
      selector: '[data-tour-id="econ-sensitivity"]' },

    { title: isAr ? 'التزامن والتصدير' : 'Sync footer · CSV export',
      body: isAr
        ? 'هنا تجد المصدر والوقت الذي تمت فيه آخر مزامنة. زر "تصدير CSV" لتحميل الـP&L الـ٥ سنوات.'
        : 'Here is where you see the source workbook and when it was last synced. The CSV export downloads the full 5-year P&L for handoff to the Anthropic Model Builder agent.',
      selector: '[data-tour-id="econ-sync"]' },

    { title: isAr ? 'انتهت الجولة' : 'End of tour',
      body: [
        isAr
          ? 'جاهز لمناقشة هذه الأرقام مع المستثمرين أو الجهة التنظيمية.'
          : 'You now know every number on this page well enough to defend it to investors or to CBUAE.',
        isAr
          ? 'لتعديل أي افتراض، حرر إكسل ثم شغّل سكريبت المزامنة.'
          : 'To edit any assumption: open the Excel workbook, change the value, and re-run the sync script.',
      ],
      position: 'center', selector: null },
  ];
}

// Microsoft Excel logo — sits on the green button as a white tile with green X
function ExcelIcon() {
  return (
    <svg width="15" height="15" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <rect x="0.5" y="0.5" width="15" height="15" rx="2" fill="#FFFFFF"/>
      <path d="M5.0 4.5 L7.6 8 L5.0 11.5 H6.6 L8.4 8.95 L10.2 11.5 H11.8 L9.2 8 L11.8 4.5 H10.2 L8.4 7.05 L6.6 4.5 Z"
            fill="#107C41"/>
    </svg>
  );
}

// Down-arrow with line under it — clear "download to disk" affordance
function DownloadArrowIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <path d="M8 2 V11 M4 7.5 L8 11.5 L12 7.5 M3.5 13.5 H12.5"
            stroke="currentColor" strokeWidth="1.6"
            fill="none" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

function StatusPill({ children, tone }) {
  const bg   = tone === 'live' ? 'var(--mal-success)' : 'var(--mal-line)';
  const fg   = tone === 'live' ? '#fff' : 'var(--mal-mid)';
  return (
    <span style={{
      fontSize: 9.5, fontWeight: 600, letterSpacing: '.06em',
      textTransform: 'uppercase', padding: '2px 6px', borderRadius: 999,
      background: bg, color: fg,
    }}>{children}</span>
  );
}

// ============================================================
// FinGroupedProductSelector — inline dropdown specifically for the
// financial section. Self-contained so it doesn't depend on cross-file
// window sharing (which Babel-standalone treats inconsistently).
// ============================================================
function FinGroupedProductSelector({ catalogue, productId, onPickProduct, isAr, isMobile }) {
  const [open, setOpen] = fS(false);
  const [hoveredId, setHoveredId] = fS(null);
  const product = window.MAL_PRODUCT_BY_ID?.[productId];
  const [expandedCats, setExpandedCats] = fS(() => ({ [product?.categoryId]: true }));
  const ref = React.useRef(null);

  const toggleCat = (id) => setExpandedCats((s) => ({ ...s, [id]: !s[id] }));

  React.useEffect(() => {
    if (!open) return;
    const onDoc = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    const onKey = (e) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', onDoc);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  React.useEffect(() => {
    if (!open || !product) return;
    setExpandedCats((s) => ({ ...s, [product.categoryId]: true }));
  }, [open, productId]);

  const categoryDot = (color) => 'var(--mal-' + (
    color === 'sky' ? 'iri-2' :
    color === 'sage' ? 'success' :
    color === 'coral' ? 'danger' :
    color === 'peach' ? 'warn' :
    color === 'ink' ? 'ink' : 'primary'
  ) + ')';

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-block' }}>
      <button onClick={() => setOpen((o) => !o)}
              aria-haspopup="menu" aria-expanded={open}
              style={{
                all: 'unset', cursor: 'pointer', boxSizing: 'border-box',
                display: 'inline-flex', alignItems: 'center', gap: 10,
                padding: '10px 16px',
                background: 'var(--mal-paper)',
                border: '1px solid var(--mal-line)',
                borderRadius: 999,
                fontSize: 13, fontWeight: 500,
                color: 'var(--mal-ink)',
                transition: 'border-color .15s, transform .15s',
                maxWidth: isMobile ? 280 : 420,
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--mal-primary-3)'; }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--mal-line)'; }}>
        <Avatar name={product?.code || '?'} tone={product?.categoryColor || 'lilac'} size={24}/>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', minWidth: 0 }}>
          <span style={{ fontSize: 9, fontWeight: 600, letterSpacing: '.08em',
                         textTransform: 'uppercase', color: 'var(--mal-mid-2)' }}>
            {product?.categoryName || ''}
          </span>
          <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
            {product?.short || (isAr ? 'اختر' : 'Select')}
          </span>
        </div>
        {product?.status === 'live' && (
          <span style={{
            fontSize: 9, fontWeight: 700, letterSpacing: '.06em',
            padding: '2px 6px', borderRadius: 999,
            background: 'var(--mal-success)', color: '#fff',
          }}>LIVE</span>
        )}
        <span style={{
          fontSize: 11, color: 'var(--mal-mid)',
          transform: open ? 'rotate(180deg)' : 'none',
          transition: 'transform .2s',
        }}>▾</span>
      </button>

      {open && (
        <div role="menu" style={{
          position: 'absolute', top: 'calc(100% + 8px)', insetInlineStart: 0,
          width: 460, maxWidth: '94vw',
          maxHeight: 600, overflowY: 'auto',
          background: 'var(--mal-paper)',
          border: '1px solid var(--mal-line)',
          borderRadius: 16,
          boxShadow: 'var(--mal-sh-3)',
          padding: 8, zIndex: 30,
          animation: 'mal-fade-up .18s ease-out',
        }}>
          <div style={{
            padding: '6px 10px 8px', fontSize: 10.5, fontWeight: 600,
            color: 'var(--mal-mid)', letterSpacing: '.08em', textTransform: 'uppercase',
            display: 'flex', justifyContent: 'space-between',
          }}>
            <span>{isAr ? 'كتالوج المنتجات' : 'Product catalogue'}</span>
            <span>{(window.MAL_PRODUCT_FLAT || []).length} {isAr ? 'منتج' : 'products'}</span>
          </div>

          {catalogue.map((cat) => {
            const expanded = !!expandedCats[cat.id];
            const liveCount = cat.products.filter((p) => p.status === 'live').length;
            return (
              <div key={cat.id} style={{ marginBottom: 4 }}>
                <button onClick={() => toggleCat(cat.id)} style={{
                  all: 'unset', cursor: 'pointer', boxSizing: 'border-box',
                  display: 'flex', alignItems: 'center', gap: 10,
                  width: '100%', padding: '10px 10px',
                  borderRadius: 10,
                  background: expanded ? 'var(--mal-surface-2)' : 'transparent',
                  transition: 'background .15s',
                }}
                onMouseEnter={(e) => { if (!expanded) e.currentTarget.style.background = 'var(--mal-surface)'; }}
                onMouseLeave={(e) => { if (!expanded) e.currentTarget.style.background = 'transparent'; }}>
                  <span style={{
                    width: 8, height: 8, borderRadius: 999,
                    background: categoryDot(cat.color),
                  }}/>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--mal-ink)' }}>
                      {cat.name}
                      {liveCount > 0 && (
                        <span style={{
                          marginInlineStart: 8, fontSize: 9, fontWeight: 700,
                          letterSpacing: '.06em', padding: '1px 5px', borderRadius: 999,
                          background: 'var(--mal-success)', color: '#fff',
                        }}>{liveCount} LIVE</span>
                      )}
                    </div>
                    <div style={{ fontSize: 11, color: 'var(--mal-mid)' }}>{cat.blurb}</div>
                  </div>
                  <span style={{ fontSize: 11, color: 'var(--mal-mid-2)', fontFamily: 'var(--mal-font-mono)' }}>
                    {cat.products.length}
                  </span>
                  <span style={{
                    fontSize: 12, color: 'var(--mal-mid)',
                    transform: expanded ? 'rotate(180deg)' : 'none',
                    transition: 'transform .2s',
                  }}>▾</span>
                </button>
                {expanded && (
                  <div style={{ paddingInlineStart: 24, paddingTop: 4 }}>
                    {cat.products.map((p) => {
                      const active = p.id === productId;
                      const isLive = p.status === 'live';
                      const showBlurb = hoveredId === p.id;
                      return (
                        <div key={p.id}>
                          <button
                            onClick={() => { onPickProduct(p.id); setOpen(false); }}
                            onMouseEnter={() => setHoveredId(p.id)}
                            onMouseLeave={() => setHoveredId(null)}
                            style={{
                              all: 'unset', boxSizing: 'border-box',
                              display: 'flex', alignItems: 'center', gap: 10,
                              width: '100%', padding: '8px 10px',
                              borderRadius: 8, cursor: 'pointer',
                              background: active ? 'var(--mal-primary-50)' : 'transparent',
                              transition: 'background .15s',
                            }}>
                            <span style={{
                              fontSize: 9, fontWeight: 700,
                              fontFamily: 'var(--mal-font-mono)',
                              color: 'var(--mal-mid-2)',
                              minWidth: 22,
                            }}>{p.code}</span>
                            <div style={{ flex: 1, minWidth: 0 }}>
                              <div style={{ fontSize: 12.5, fontWeight: 500,
                                            color: isLive ? 'var(--mal-ink)' : 'var(--mal-mid)' }}>
                                {p.short}
                              </div>
                            </div>
                            {isLive && (
                              <span style={{
                                fontSize: 9, fontWeight: 700, letterSpacing: '.06em',
                                padding: '1px 5px', borderRadius: 999,
                                background: 'var(--mal-success)', color: '#fff',
                              }}>LIVE</span>
                            )}
                            {!isLive && (
                              <span style={{
                                fontSize: 9, fontWeight: 600, letterSpacing: '.06em',
                                padding: '1px 5px', borderRadius: 999,
                                background: 'var(--mal-line)', color: 'var(--mal-mid)',
                                textTransform: 'uppercase',
                              }}>{isAr ? 'قيد الإعداد' : 'In progress'}</span>
                            )}
                            {active && <span style={{ color: 'var(--mal-primary)', fontSize: 12 }}>●</span>}
                          </button>
                          {showBlurb && p.blurb && (
                            <div style={{
                              padding: '0 14px 8px 32px', fontSize: 11.5, lineHeight: 1.55,
                              color: 'var(--mal-mid)', maxWidth: 400,
                            }}>
                              {p.blurb}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ============================================================
// In-progress card (P2/P3/P4)
// ============================================================
function InProgressCard({ product, isAr }) {
  return (
    <div className="mal-fade-up" style={{
      position: 'relative',
      background: 'var(--mal-paper)',
      border: '1px dashed var(--mal-line)',
      borderRadius: 'var(--mal-r-lg)',
      padding: 56,
      minHeight: 380,
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      overflow: 'hidden',
    }}>
      <div aria-hidden style={{
        position: 'absolute', inset: 0,
        background: 'repeating-linear-gradient(135deg, transparent 0 12px, rgba(26,26,40,.025) 12px 24px)',
        pointerEvents: 'none',
      }}/>
      <div style={{ textAlign: 'center', position: 'relative', maxWidth: 520 }}>
        <Avatar name={product.code} tone={product.categoryColor || product.color || 'lilac'} size={64}/>
        <div style={{ marginTop: 18, fontSize: 11, fontWeight: 600,
                      letterSpacing: '.08em', textTransform: 'uppercase',
                      color: 'var(--mal-mid-2)' }}>
          {product.categoryName || product.code} · {isAr ? 'قيد الإعداد' : 'In progress'}
        </div>
        <div style={{
          fontFamily: 'var(--mal-font-display)', fontStyle: 'italic',
          fontSize: 32, lineHeight: 1.1, letterSpacing: '-0.02em',
          margin: '8px 0 14px',
        }}>{product.title}</div>
        <p style={{ fontSize: 14, lineHeight: 1.7, color: 'var(--mal-mid)' }}>
          {product.blurb}
        </p>
        <div style={{ marginTop: 24, display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap' }}>
          <Pill tone="neutral" dot>
            {isAr ? 'الافتراضات قيد التحقق' : 'Assumptions under validation'}
          </Pill>
          <Pill tone="neutral">
            {isAr ? 'المنتج النشط: Smart Invoice' : 'Live product: Smart Invoice'}
          </Pill>
        </div>
      </div>
    </div>
  );
}

// ============================================================
// P1 Workbench — scenario picker (interactive) + dashboard (read-only)
// ============================================================
function P1Workbench({ data, isMobile, isAr }) {
  const [scenario, setScenario] = fS('base');
  const scen = data.scenarios[scenario];

  const exportCsv = fCB(() => {
    const yrs = ['y1','y2','y3','y4','y5'];
    const cols = ['avgBook','grossInt','fundingCost','nim','lossProvision','ram','opex','netContrib','equity'];
    const head = ['Line', ...yrs.map((y) => y.toUpperCase())].join(',');
    const rows = cols.map((k) => [k, ...yrs.map((y) => data.pnl[y][k].toFixed(2))].join(','));
    const csv = [head, ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob); a.download = 'mal-p1-pnl-5yr.csv'; a.click();
  }, [data]);

  return (
    <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '320px 1fr', gap: 24, alignItems: 'start' }}>
      {/* ============= LEFT: sticky lever panel ============= */}
      <StickyLeverPanel data={data} isMobile={isMobile} isAr={isAr}/>

      {/* ============= RIGHT: dashboard ============= */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 22, minWidth: 0 }}>
        <HeroKpis data={data} isAr={isAr}/>
        <ScenarioPickerBar scenario={scenario} setScenario={setScenario} scen={scen}
                           data={data} isAr={isAr}/>
        <DisbursementSection data={data} isMobile={isMobile} isAr={isAr}/>
        <PLSection data={data} isMobile={isMobile} isAr={isAr}/>
        <RiskSection data={data} isMobile={isMobile} isAr={isAr}/>
        <CapitalFundingSection data={data} isMobile={isMobile} isAr={isAr}/>
        <UnitEconomicsSection data={data} isMobile={isMobile} isAr={isAr}/>
        <VintageCohortsSection data={data} isMobile={isMobile} isAr={isAr}/>
        <ScenarioCompareSection data={data} isAr={isAr}/>
        <BreakEvenSection data={data} isAr={isAr}/>
        <SensitivitySection data={data} isAr={isAr}/>
        <SyncFooter data={data} exportCsv={exportCsv} isAr={isAr}/>
      </div>
    </div>
  );
}

// ============================================================
// Hero KPIs (5-yr summary)
// ============================================================
function HeroKpis({ data, isAr }) {
  const fy = data.fiveYearSummary;
  const r3 = data.ratios.y3;
  return (
    <div data-tour-id="econ-hero" className="mal-fade-up" style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
      <MalKpi label={isAr ? 'الصرف ٥ سنوات (وجه)' : '5-yr disbursement (face)'}
              value={aedB(fy.face, 1)}
              sub={isAr ? '٢٥٠M → ١٣B' : 'Y1 250M → Y5 13B'}/>
      <MalKpi label={isAr ? 'مساهمة صافية تراكمية' : 'Cum. net contribution'}
              value={aedM(fy.cumNetContrib, 0)}
              sub={isAr ? '٥ سنوات' : 'Y1 → Y5'}/>
      <MalKpi label={isAr ? 'العائد على الأصول · Y3' : 'ROA · Y3'}
              value={pct(r3.roaPct, 2)}
              deltaTone={r3.roaPct >= 5 ? 'up' : 'down'}
              sub={isAr ? `Y5: ${pct(data.ratios.y5.roaPct, 2)}` : `Y5: ${pct(data.ratios.y5.roaPct, 2)}`}/>
      <MalKpi label={isAr ? 'العائد المعدل بالمخاطر · Y3' : 'RAROC · Y3'}
              value={pct(r3.rarocPct, 0)}
              deltaTone={r3.rarocPct >= 20 ? 'up' : 'down'}
              sub={isAr ? 'مقابل ٢٠٪ هدف' : 'vs 20% target'}/>
      <MalKpi label={isAr ? 'حقوق الملكية المرفوعة' : 'Equity raised (cum.)'}
              value={aedM(fy.totalEquityRaised, 0)}
              sub={isAr ? 'بذرة + سلسلة A/B/C' : 'Seed + A + B + C'}/>
      <MalKpi label={isAr ? 'الكتاب الذروة (Y5)' : 'Peak avg book (Y5)'}
              value={aedB(fy.avgBookPeak, 1)}
              sub={isAr ? 'متوسط' : 'avg'}/>
    </div>
  );
}

// ============================================================
// Scenario picker bar — pills + Y3 readout
// ============================================================
function ScenarioPickerBar({ scenario, setScenario, scen, data, isAr }) {
  const base = data.scenarios.base;
  const delta = (k) => scen[k] - base[k];
  const pctDelta = (k) => base[k] !== 0 ? ((scen[k] / base[k] - 1) * 100) : 0;
  return (
    <div data-tour-id="econ-scenarios" className="mal-fade-up" style={{
      background: 'var(--mal-paper)', border: '1px solid var(--mal-line)',
      borderRadius: 'var(--mal-r-lg)', padding: 18,
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12, marginBottom: 14 }}>
        <div>
          <div style={{ fontSize: 13, fontWeight: 600 }}>
            {isAr ? 'لوحة السيناريوهات · Y3' : 'Scenario panel · Y3 readout'}
          </div>
          <div style={{ fontSize: 11, color: 'var(--mal-mid)', marginTop: 2 }}>
            {isAr ? 'انقر للتبديل · القيم محسوبة مسبقاً في إكسل' : 'Click to switch · values pre-computed in Excel (Scenarios tab)'}
          </div>
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          {SCENARIOS.map((s) => (
            <button key={s.key} onClick={() => setScenario(s.key)} style={{
              all: 'unset', cursor: 'pointer',
              padding: '8px 14px', borderRadius: 999,
              fontSize: 12, fontWeight: 600,
              background: scenario === s.key ? 'var(--mal-ink)' : 'var(--mal-surface-2)',
              color: scenario === s.key ? '#FAF7EE' : 'var(--mal-ink)',
              border: '1px solid var(--mal-line)',
              transition: 'all .15s',
            }}>{s.label}</button>
          ))}
        </div>
      </div>
      <div style={{ display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
                    gap: 10, marginTop: 6 }}>
        <ScenarioTile label={isAr ? 'كتاب Y3' : 'Y3 book'} v={aedM(scen.totalBook, 0)} d={pctDelta('totalBook')}/>
        <ScenarioTile label={isAr ? 'إيراد إجمالي' : 'Gross int.'} v={aedM(scen.grossInt, 1)} d={pctDelta('grossInt')}/>
        <ScenarioTile label="NIM" v={aedM(scen.nim, 1)} d={pctDelta('nim')}/>
        <ScenarioTile label={isAr ? 'الخسارة' : 'Loss'} v={aedM(scen.loss, 1)} d={pctDelta('loss')} invertedDelta/>
        <ScenarioTile label="OpEx" v={aedM(scen.opex, 1)} d={pctDelta('opex')} invertedDelta/>
        <ScenarioTile label={isAr ? 'مساهمة صافية' : 'Net contrib'} v={aedM(scen.netContrib, 1)} d={pctDelta('netContrib')}/>
        <ScenarioTile label="ROA" v={pct(scen.roaPct * 100, 2)} d={((scen.roaPct - base.roaPct) * 100).toFixed(2) + ' pts'} raw/>
        <ScenarioTile label="RAROC" v={pct(scen.rarocPct * 100, 1)} d={((scen.rarocPct - base.rarocPct) * 100).toFixed(1) + ' pts'} raw/>
      </div>
    </div>
  );
}

function ScenarioTile({ label, v, d, invertedDelta = false, raw = false }) {
  const positive = raw ? !d.startsWith('-') : (invertedDelta ? d <= 0 : d >= 0);
  const tone = positive ? 'var(--mal-success)' : 'var(--mal-danger)';
  return (
    <div style={{
      padding: '10px 12px', borderRadius: 12,
      background: 'var(--mal-surface-2)', border: '1px solid var(--mal-line-2)',
    }}>
      <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--mal-mid-2)',
                    textTransform: 'uppercase', letterSpacing: '.06em' }}>{label}</div>
      <div style={{ fontFamily: 'var(--mal-font-display)', fontStyle: 'italic',
                    fontSize: 18, lineHeight: 1.1, marginTop: 4 }}>{v}</div>
      <div style={{ fontSize: 10.5, color: tone, marginTop: 2, fontWeight: 500 }}>
        {raw ? d : (typeof d === 'number' ? (d >= 0 ? '+' : '') + d.toFixed(1) + '%' : d)}
      </div>
    </div>
  );
}

// ============================================================
// Disbursement section — 5-yr stacked + composition
// ============================================================
function DisbursementSection({ data, isMobile, isAr }) {
  const yrs = ['y1','y2','y3','y4','y5'];
  const tracks = data.tracks;
  return (
    <div data-tour-id="econ-disb" style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '2fr 1fr', gap: 22 }}>
      <ChartCard title={isAr ? 'الصرف ٥ سنوات (AED M)' : 'Disbursement plan · Y1 → Y5 (AED M)'}
                 sub={isAr ? 'صرف وجه الفاتورة (face value)' : 'Face value of invoices funded'}>
        <MalBarChart
          height={220}
          data={yrs.map((y) => ({
            label: y.toUpperCase(),
            value: data.disbursement[y].face,
            tone: 'iri',
          }))}
          formatValue={(v) => v >= 1000 ? (v/1000).toFixed(1) + 'B' : v.toFixed(0) + 'M'}
        />
      </ChartCard>
      <ChartCard title={isAr ? 'تكوين الكتاب · Y3' : 'Book composition · Y3'}
                 sub={isAr ? 'مرجح بالخليط × المدة' : 'Weighted by mix × tenor'}>
        <MalStackedBar
          segments={[
            { label: 'Pay-30',    value: tracks.pay30.y3.avgBook, color: 'var(--mal-primary)' },
            { label: 'BNPL',      value: tracks.bnpl.y3.avgBook,  color: 'var(--mal-primary-3)' },
            { label: 'Extension', value: tracks.ext.y3.avgBook,   color: 'var(--mal-iri-2)' },
          ]}
          formatLabel={(v) => v.toFixed(0) + 'M'}
        />
        <div style={{ marginTop: 14, fontSize: 11.5, lineHeight: 1.6, color: 'var(--mal-mid)' }}>
          {isAr
            ? `BNPL تحمل ٦٤٪ من الكتاب · المدة ١٠٥ يوم`
            : `BNPL carries 64% of book · 105-day tenor`}
        </div>
      </ChartCard>
    </div>
  );
}

// ============================================================
// P&L section — margin walk + 5-yr table
// ============================================================
function PLSection({ data, isMobile, isAr }) {
  const r3 = data.ratios.y3;
  const yrs = ['y1','y2','y3','y4','y5'];
  return (
    <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 22 }}>
      <div data-tour-id="econ-margin">
      <ChartCard title={isAr ? 'تدرج الهامش · Y3 (% الكتاب)' : 'Margin walk · Y3 (% of book)'}
                 sub={isAr ? 'إجمالي → بعد التكلفة → بعد الخسائر → الصافي' : 'Gross → −CoF → −Loss → −OpEx → Net'}>
        <MalBarChart
          height={240}
          data={[
            { label: 'Gross',  value: +(r3.nimPct + (r3.lossPct - r3.lossPct) + 6.5).toFixed(2), tone: 'iri' },
            { label: '− CoF',  value: +r3.nimPct.toFixed(2), tone: 'iri' },
            { label: '− Loss', value: +(r3.nimPct - r3.lossPct).toFixed(2), tone: 'iri' },
            { label: '− OpEx', value: +(r3.nimPct - r3.lossPct - r3.opexPct).toFixed(2), tone: 'success' },
          ]}
          formatValue={(v) => v.toFixed(1) + '%'}
        />
        <div style={{ marginTop: 12, fontSize: 11.5, color: 'var(--mal-mid)', lineHeight: 1.6 }}>
          ROA Y3: <strong>{pct(r3.roaPct, 2)}</strong> · RAROC: <strong>{pct(r3.rarocPct, 0)}</strong>
        </div>
      </ChartCard>
      </div>
      <ChartCard title={isAr ? 'المساهمة الصافية ٥ سنوات' : 'Net contribution · Y1 → Y5 (AED M)'}>
        <MalLineChart
          height={240}
          labels={yrs.map((y) => y.toUpperCase())}
          series={[{ name: 'NC', values: yrs.map((y) => data.pnl[y].netContrib),
                     color: 'var(--mal-primary)' }]}
          formatValue={(v) => v.toFixed(0) + 'M'}
        />
        <div style={{ marginTop: 12, fontSize: 11.5, color: 'var(--mal-mid)', lineHeight: 1.6 }}>
          {isAr ? 'تراكمي ٥ سنوات: ' : 'Cumulative Y1→Y5: '}
          <strong>{aedM(data.fiveYearSummary.cumNetContrib, 0)}</strong>
        </div>
      </ChartCard>
      <div data-tour-id="econ-pnl-table" style={{ gridColumn: isMobile ? 'auto' : '1 / -1' }}>
        <PnLTable data={data} isAr={isAr}/>
      </div>
    </div>
  );
}

function PnLTable({ data, isAr }) {
  const yrs = ['y1','y2','y3','y4','y5'];
  const rows = [
    [isAr ? 'متوسط الكتاب' : 'Avg book',                 'avgBook',       false],
    [isAr ? 'إيراد إجمالي' : 'Gross interest income',    'grossInt',      false],
    [isAr ? 'تكلفة التمويل' : '− Funding cost',          'fundingCost',   true],
    [isAr ? 'NIM' : 'NIM',                               'nim',           false, 'total'],
    [isAr ? 'مخصص الخسائر' : '− Loss provision',         'lossProvision', true],
    [isAr ? 'هامش معدل بالمخاطر' : 'Risk-adjusted margin','ram',          false, 'total'],
    [isAr ? 'مصاريف التشغيل' : '− OpEx',                'opex',           true],
    [isAr ? 'المساهمة الصافية' : 'Net contribution',     'netContrib',    false, 'total'],
    [isAr ? 'حقوق الملكية المخصصة' : 'Equity allocated', 'equity',        false, 'sub'],
  ];
  return (
    <ChartCard title={isAr ? 'الربح والخسارة ٥ سنوات (AED M)' : 'Pro-forma P&L · Y1 → Y5 (AED M)'}>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%', fontSize: 13 }}>
          <thead>
            <tr>
              <th style={th({ first: true })}/>
              {yrs.map((y) => (
                <th key={y} style={th()}>{y.toUpperCase()}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map(([label, key, neg, role], ri) => (
              <tr key={ri} style={{
                background: role === 'total' ? 'var(--mal-primary-50)' : 'transparent',
                fontWeight: role === 'total' ? 600 : 400,
              }}>
                <td style={td({ label: true, sub: role === 'sub' })}>{label}</td>
                {yrs.map((y) => {
                  const v = data.pnl[y][key];
                  const display = neg ? -v : v;
                  return (
                    <td key={y} style={td({ negative: display < 0 })}>{display.toFixed(1)}</td>
                  );
                })}
              </tr>
            ))}
            {/* Ratios row */}
            <tr style={{ background: 'var(--mal-surface-2)' }}>
              <td style={td({ label: true, role: 'header' })}>{isAr ? 'العائد على الأصول' : 'ROA (%)'}</td>
              {yrs.map((y) => <td key={y} style={td()}>{pct(data.ratios[y].roaPct, 2)}</td>)}
            </tr>
            <tr style={{ background: 'var(--mal-surface-2)' }}>
              <td style={td({ label: true })}>RAROC (%)</td>
              {yrs.map((y) => <td key={y} style={td()}>{pct(data.ratios[y].rarocPct, 1)}</td>)}
            </tr>
          </tbody>
        </table>
      </div>
    </ChartCard>
  );
}

// ============================================================
// Risk section — PD/LGD/EAD per track + stress
// ============================================================
function RiskSection({ data, isMobile, isAr }) {
  const r = data.risk;
  return (
    <div data-tour-id="econ-risk-card">
    <ChartCard title={isAr ? 'طبقة المخاطر · PD/LGD/EAD لكل مسار' : 'Risk layer · PD/LGD/EAD per track'}
               sub={isAr ? 'إطار Basel III IRB Foundation · EL = PD × LGD × EAD' : 'Basel III IRB Foundation · EL = PD × LGD × EAD'}>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%', fontSize: 13 }}>
          <thead>
            <tr>
              <th style={th({ first: true })}>{isAr ? 'المعيار' : 'Parameter'}</th>
              <th style={th()}>Pay-30</th>
              <th style={th()}>BNPL</th>
              <th style={th()}>{isAr ? 'تمديد' : 'Extension'}</th>
              <th style={th()}>{isAr ? 'مرجح' : 'Weighted'}</th>
              <th style={th()}>{isAr ? 'إجهاد ١.٥×' : 'Stress 1.5×'}</th>
            </tr>
          </thead>
          <tbody>
            <RiskRow label={isAr ? 'PD (٪/سنة)' : 'PD (% p.a.)'}
                     v1={r.pay30.pd} v2={r.bnpl.pd} v3={r.ext.pd}
                     w={(r.pay30.pd * 0.4 + r.bnpl.pd * 0.5 + r.ext.pd * 0.1)}
                     stress={r.pay30.stressed * 100 / r.pay30.pd ? 1.5 : 1.5}
                     stressLabel="× 1.5"/>
            <RiskRow label={isAr ? 'LGD (٪)' : 'LGD (%)'}
                     v1={r.pay30.lgd} v2={r.bnpl.lgd} v3={r.ext.lgd}
                     w={(r.pay30.lgd * 0.4 + r.bnpl.lgd * 0.5 + r.ext.lgd * 0.1)}
                     stressLabel="—"/>
            <RiskRow label="EAD (%)"
                     v1={r.pay30.ead} v2={r.bnpl.ead} v3={r.ext.ead}
                     w={(r.pay30.ead * 0.4 + r.bnpl.ead * 0.5 + r.ext.ead * 0.1)}
                     stressLabel="—"/>
            <tr style={{ background: 'var(--mal-primary-50)', fontWeight: 600 }}>
              <td style={td({ label: true })}>{isAr ? 'معدل الخسارة الصافي' : 'Net loss rate (% of book)'}</td>
              <td style={td()}>{pct(r.pay30.netLoss, 2)}</td>
              <td style={td()}>{pct(r.bnpl.netLoss, 2)}</td>
              <td style={td()}>{pct(r.ext.netLoss, 2)}</td>
              <td style={td()}>{pct(r.pay30.netLoss * 0.4 + r.bnpl.netLoss * 0.5 + r.ext.netLoss * 0.1, 2)}</td>
              <td style={td({ tone: 'danger' })}>{pct(r.pay30.stressed * 0.4 + r.bnpl.stressed * 0.5 + r.ext.stressed * 0.1, 2)}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div style={{ marginTop: 14, padding: 12, background: 'var(--mal-surface-2)',
                    borderRadius: 10, fontSize: 11.5, color: 'var(--mal-mid)', lineHeight: 1.65 }}>
        {isAr
          ? 'الخسارة المرجحة المتوقعة ٢.٦٪ من الكتاب · إجهاد CBUAE ٢٠٢٠ (PD ×١.٥) يرفعها إلى ٤.٠٪ — لا تزال مغطاة بالهامش.'
          : 'Weighted expected loss 2.6% of book · CBUAE-2020 stress (PD ×1.5) lifts to ~4.0% — still margin-covered.'}
      </div>
    </ChartCard>
    </div>
  );
}

function RiskRow({ label, v1, v2, v3, w, stressLabel }) {
  return (
    <tr>
      <td style={td({ label: true })}>{label}</td>
      <td style={td()}>{v1.toFixed(1)}</td>
      <td style={td()}>{v2.toFixed(1)}</td>
      <td style={td()}>{v3.toFixed(1)}</td>
      <td style={td()}>{w.toFixed(1)}</td>
      <td style={td({ tone: 'muted' })}>{stressLabel}</td>
    </tr>
  );
}

// ============================================================
// Capital plan + funding stack
// ============================================================
function CapitalFundingSection({ data, isMobile, isAr }) {
  return (
    <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 22 }}>
      <CapitalPlanCard data={data} isAr={isAr}/>
      <FundingStackCard data={data} isAr={isAr}/>
    </div>
  );
}

function CapitalPlanCard({ data, isAr }) {
  const yrs = ['y1','y2','y3','y4','y5'];
  const cap = data.capitalPlan;
  return (
    <div data-tour-id="econ-capital">
    <ChartCard title={isAr ? 'خطة رأس المال · ٥ سنوات' : 'Capital plan · 5-year'}
               sub={isAr ? 'CET1 ١٣٪ هدف · جولات تمويل: بذرة + سلسلة A/B/C' : 'CBUAE Tier-1 ≥13% · Seed → Series A/B/C'}>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%', fontSize: 12.5 }}>
          <thead>
            <tr>
              <th style={th({ first: true })}/>
              {yrs.map((y) => <th key={y} style={th()}>{y.toUpperCase()}</th>)}
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={td({ label: true })}>{isAr ? 'حقوق ملكية مطلوبة' : 'Required equity'}</td>
              {yrs.map((y) => <td key={y} style={td()}>{aedM(cap[y].requiredEq, 0)}</td>)}
            </tr>
            <tr>
              <td style={td({ label: true })}>{isAr ? 'مرفوع في السنة' : 'Raised in year'}</td>
              {yrs.map((y) => <td key={y} style={td({ tone: cap[y].raisedYear > 0 ? 'success' : 'muted' })}>
                {cap[y].raisedYear > 0 ? aedM(cap[y].raisedYear, 0) : '—'}
              </td>)}
            </tr>
            <tr>
              <td style={td({ label: true })}>{isAr ? 'تراكمي مرفوع' : 'Cumulative raised'}</td>
              {yrs.map((y) => <td key={y} style={td()}>{aedM(cap[y].cumulativeRaised, 0)}</td>)}
            </tr>
            <tr>
              <td style={td({ label: true })}>{isAr ? 'أرباح محتجزة' : 'Retained earnings'}</td>
              {yrs.map((y) => <td key={y} style={td()}>{aedM(cap[y].retainedEarnings, 0)}</td>)}
            </tr>
            <tr style={{ background: 'var(--mal-primary-50)', fontWeight: 600 }}>
              <td style={td({ label: true })}>{isAr ? 'حقوق ملكية متاحة' : 'Total available equity'}</td>
              {yrs.map((y) => <td key={y} style={td()}>{aedM(cap[y].totalAvailEq, 0)}</td>)}
            </tr>
            <tr>
              <td style={td({ label: true })}>{isAr ? 'الفائض' : 'Headroom'}</td>
              {yrs.map((y) => <td key={y} style={td({ tone: cap[y].headroom >= 0 ? 'success' : 'danger' })}>
                {aedM(cap[y].headroom, 0)}</td>)}
            </tr>
            <tr>
              <td style={td({ label: true })}>{isAr ? 'نسبة Tier-1' : 'Tier-1 ratio'}</td>
              {yrs.map((y) => <td key={y} style={td()}>{pct(cap[y].tier1Ratio * 100, 0)}</td>)}
            </tr>
            <tr>
              <td style={td({ label: true })}>{isAr ? 'الحالة' : 'Status'}</td>
              {yrs.map((y) => <td key={y} style={td({ tone: cap[y].tier1Status.includes('PASS') ? 'success' : 'danger' })}>
                {cap[y].tier1Status.replace('✓ ', '')}
              </td>)}
            </tr>
          </tbody>
        </table>
      </div>
    </ChartCard>
    </div>
  );
}

function FundingStackCard({ data, isAr }) {
  const f = data.fundingStack;
  const yrs = ['y1','y2','y3','y4','y5'];
  return (
    <div data-tour-id="econ-funding">
    <ChartCard title={isAr ? 'هيكل التمويل · شلال السيولة' : 'Funding stack · liability waterfall'}
               sub={isAr ? `تكلفة مرجحة ${pct(f.blendedCof, 2)} · الافتراض ${pct(f.inputsCof, 1)}`
                          : `Blended COF ${pct(f.blendedCof, 2)} vs assumed ${pct(f.inputsCof, 1)}`}>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%', fontSize: 12.5 }}>
          <thead>
            <tr>
              <th style={th({ first: true })}>{isAr ? 'الشريحة' : 'Tranche'}</th>
              <th style={th()}>{isAr ? 'الحصة' : 'Share'}</th>
              <th style={th()}>{isAr ? 'فرق' : 'Spread'}</th>
              <th style={th()}>{isAr ? 'كلي' : 'All-in'}</th>
            </tr>
          </thead>
          <tbody>
            {f.tranches.map((t, i) => (
              <tr key={i}>
                <td style={td({ label: true })}>{t.name}</td>
                <td style={td()}>{pct(t.share * 100, 0)}</td>
                <td style={td()}>{t.spread ? '+' + t.spread + 'bps' : '—'}</td>
                <td style={td()}>{t.allIn ? pct(t.allIn * 100, 1) : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div style={{ marginTop: 14 }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--mal-mid-2)',
                      textTransform: 'uppercase', letterSpacing: '.06em', marginBottom: 6 }}>
          {isAr ? 'العهود التنظيمية' : 'Covenant tests'}
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 6 }}>
          {[['Senior ≤ 85%', f.covenants.seniorCap[2]],
            ['Single-obligor ≤ 10%', f.covenants.singleObligor[2]],
            ['Tier-1 ≥ 13%', f.covenants.tier1Floor[2]]
          ].map(([label, status], i) => (
            <div key={i} style={{
              padding: 10, borderRadius: 10, fontSize: 11,
              background: 'var(--mal-surface-2)', border: '1px solid var(--mal-line-2)',
            }}>
              <div style={{ color: 'var(--mal-mid)', marginBottom: 2 }}>{label}</div>
              <div style={{ color: String(status).includes('PASS') ? 'var(--mal-success)' : 'var(--mal-danger)',
                            fontWeight: 600 }}>
                {String(status).replace('✓ ', '✓ ')}
              </div>
            </div>
          ))}
        </div>
      </div>
    </ChartCard>
    </div>
  );
}

// ============================================================
// Unit Economics — per AED 100k by track
// ============================================================
function UnitEconomicsSection({ data, isMobile, isAr }) {
  const ue = data.unitEconomics;
  const tracks = [
    ['Pay-30',    ue.pay30],
    ['BNPL',      ue.bnpl],
    [isAr ? 'تمديد' : 'Extension', ue.ext],
  ];
  return (
    <div data-tour-id="econ-unit-econ">
    <ChartCard title={isAr ? 'الاقتصاد الوحدوي · لكل ١٠٠ ألف درهم فاتورة' : 'Unit economics · per AED 100k of invoice'}
               sub={isAr ? 'مساهمة لكل فاتورة حسب المسار · لجنة التسعير' : 'Per-invoice contribution by track · for pricing committee'}>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%', fontSize: 13 }}>
          <thead>
            <tr>
              <th style={th({ first: true })}>{isAr ? 'البند' : 'Line'}</th>
              {tracks.map(([name]) => <th key={name} style={th()}>{name}</th>)}
            </tr>
          </thead>
          <tbody>
            {[
              [isAr ? 'فاتورة' : 'Invoice face',  'face',         (v) => 'AED ' + v.toLocaleString()],
              [isAr ? 'متقدم' : 'Advanced',        'advanced',     (v) => 'AED ' + v.toLocaleString()],
              [isAr ? 'مدة (يوم)' : 'Tenor (days)', 'tenor',       (v) => v.toFixed(0)],
              [isAr ? 'العائد %APR' : 'Yield (% APR)', 'yieldPct', (v) => pct(v, 1)],
              [isAr ? 'رسم إجمالي' : 'Gross fee',  'grossFee',    (v) => 'AED ' + Math.round(v).toLocaleString()],
              [isAr ? 'تكلفة تمويل' : '− Funding cost', 'fundingCost', (v) => '(AED ' + Math.round(v).toLocaleString() + ')'],
              ['NIM',                              'nim',         (v) => 'AED ' + Math.round(v).toLocaleString()],
              [isAr ? 'خسارة متوقعة' : '− Expected loss', 'expectedLoss', (v) => '(AED ' + Math.round(v).toLocaleString() + ')'],
              [isAr ? 'هامش معدل' : 'Risk-adj margin', 'ram',     (v) => 'AED ' + Math.round(v).toLocaleString()],
              [isAr ? 'تشغيل' : '− OpEx',          'opex',        (v) => '(AED ' + Math.round(v).toLocaleString() + ')'],
              [isAr ? 'مساهمة صافية' : 'Net contribution', 'netContrib', (v) => 'AED ' + Math.round(v).toLocaleString()],
              [isAr ? 'هامش %' : 'Margin (% of face)', 'netContribPct', (v) => pct(v, 2)],
            ].map(([label, key, fmt], ri) => {
              const total = key === 'netContrib' || key === 'netContribPct' || key === 'ram' || key === 'nim';
              return (
                <tr key={ri} style={{
                  background: total ? 'var(--mal-primary-50)' : 'transparent',
                  fontWeight: total ? 600 : 400,
                }}>
                  <td style={td({ label: true })}>{label}</td>
                  {tracks.map(([name, t]) => <td key={name} style={td()}>{fmt(t[key])}</td>)}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </ChartCard>
    </div>
  );
}

// ============================================================
// Vintage cohorts
// ============================================================
function VintageCohortsSection({ data, isMobile, isAr }) {
  const v = data.vintage;
  return (
    <div data-tour-id="econ-vintage" style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 22 }}>
      <ChartCard title={isAr ? 'الخسارة التراكمية · شهر بعد شهر' : 'Cumulative loss curve · M0 → M24'}
                 sub={isAr ? 'لوغاريتمي · ٣٠٪ في M0–6 · ٥٠٪ M7–18 · ٢٠٪ M19–24'
                            : 'Lognormal: 30% M0–6 · 50% M7–18 · 20% M19–24'}>
        <VintageLossSvg vintage={v}/>
      </ChartCard>
      <ChartCard title={isAr ? 'الخسارة العمرية لكل دفعة' : 'Lifetime loss per vintage'}
                 sub={isAr ? `إجمالي ٣ سنوات: ${aedM(v.totalLifetimeLoss, 1)} على ${aedM(v.totalAdvanced, 0)} مستحق`
                            : `Y1+Y2+Y3 total: ${aedM(v.totalLifetimeLoss, 1)} on ${aedM(v.totalAdvanced, 0)} advanced`}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginTop: 6 }}>
          {['y1','y2','y3'].map((y) => {
            const vt = v.perVintage[y];
            const max = Math.max(...['y1','y2','y3'].map((k) => v.perVintage[k].lossM));
            const w = (vt.lossM / max) * 100;
            return (
              <div key={y}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                  <span style={{ color: 'var(--mal-mid)' }}>{y.toUpperCase()} {isAr ? 'دفعة' : 'vintage'}</span>
                  <span style={{ fontFamily: 'var(--mal-font-mono)' }}>
                    {aedM(vt.lossM, 1)} <span style={{ color: 'var(--mal-mid)' }}>· {pct(vt.lossPct * 100, 2)}</span>
                  </span>
                </div>
                <div style={{ height: 10, borderRadius: 999, background: 'var(--mal-surface-2)', overflow: 'hidden' }}>
                  <div style={{ width: w + '%', height: '100%', background: 'var(--mal-primary)' }}/>
                </div>
                <div style={{ fontSize: 10.5, color: 'var(--mal-mid-2)', marginTop: 2 }}>
                  {isAr ? 'مستحق' : 'advanced'}: {aedM(vt.advanced, 0)}
                </div>
              </div>
            );
          })}
        </div>
        <div style={{ marginTop: 14, padding: 12, background: 'var(--mal-surface-2)', borderRadius: 10, fontSize: 11.5, color: 'var(--mal-mid)', lineHeight: 1.6 }}>
          {isAr
            ? 'الخسارة العمرية ٠.٦٠٪ من المستحق — منخفضة جداً · يعكس ضمان الفاتورة'
            : 'Lifetime loss ratio 0.60% of advanced — very low · reflects invoice collateral'}
        </div>
      </ChartCard>
    </div>
  );
}

// ============================================================
// Scenario compare table
// ============================================================
function ScenarioCompareSection({ data, isAr }) {
  const order = ['stress','downside','base','upside'];
  const rows = [
    [isAr ? 'الصرف Y3' : 'Disbursement Y3', 'disbY3',     (v) => aedM(v, 0)],
    [isAr ? 'الكتاب Y3' : 'Book Y3',         'totalBook', (v) => aedM(v, 0)],
    [isAr ? 'إيراد إجمالي' : 'Gross interest','grossInt', (v) => aedM(v, 1)],
    ['NIM',                                  'nim',       (v) => aedM(v, 1)],
    [isAr ? 'الخسارة' : 'Loss provision',    'loss',      (v) => aedM(v, 1)],
    ['OpEx',                                 'opex',      (v) => aedM(v, 1)],
    [isAr ? 'مساهمة صافية' : 'Net contribution','netContrib',(v) => aedM(v, 1)],
    [isAr ? 'العائد على الأصول' : 'ROA Y3',  'roaPct',    (v) => pct(v * 100, 2)],
    ['RAROC Y3',                              'rarocPct', (v) => pct(v * 100, 1)],
  ];
  return (
    <div data-tour-id="econ-scen-compare">
    <ChartCard title={isAr ? 'مقارنة السيناريوهات · Y3' : 'Scenario comparison · Y3'}
               sub={isAr ? 'إجهاد ← تراجع ← أساس ← صعود' : 'Stress ← Downside ← Base ← Upside'}>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%', fontSize: 12.5 }}>
          <thead>
            <tr>
              <th style={th({ first: true })}/>
              {order.map((s) => (
                <th key={s} style={{ ...th(), background: s === 'base' ? 'var(--mal-primary-50)' : 'transparent' }}>
                  {SCENARIOS.find((sc) => sc.key === s).label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map(([label, key, fmt], ri) => (
              <tr key={ri}>
                <td style={td({ label: true })}>{label}</td>
                {order.map((s) => (
                  <td key={s} style={{
                    ...td(),
                    background: s === 'base' ? 'var(--mal-primary-50)' : 'transparent',
                    fontWeight: s === 'base' ? 600 : 400,
                  }}>{fmt(data.scenarios[s][key])}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </ChartCard>
    </div>
  );
}

// ============================================================
// Break-even readout
// ============================================================
function BreakEvenSection({ data, isAr }) {
  const be = data.breakEven;
  return (
    <div data-tour-id="econ-breakeven">
    <ChartCard title={isAr ? 'تحليل التعادل' : 'Break-even readout'}
               sub={isAr ? 'تحلل جبري — دون Goal Seek' : 'Algebraic — no Goal Seek required'}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 }}>
        <BeBlock title={isAr ? 'تعادل صرف Y2' : 'Y2 disbursement break-even'}
                 main={aedM(be.y2BE, 0)}
                 sub={isAr ? `مقابل ${aedM(be.y2Plan, 0)} مخطط · فائض ${aedM(be.y2Headroom, 0)}` : `vs ${aedM(be.y2Plan, 0)} plan · headroom ${aedM(be.y2Headroom, 0)}`}
                 status={String(be.y2Status).replace('✓ ', '')} tone="success"/>
        <BeBlock title={isAr ? 'تحمل إجهاد PD · Y3' : 'PD-stress tolerance · Y3'}
                 main={ratio(be.pdMultiplier, 2)}
                 sub={String(be.pdShift)}
                 status={String(be.vsStress).replace('✓ ', '')} tone="success"/>
        <BeBlock title={isAr ? 'هدف العائد على الأصول' : 'ROA target'}
                 main={pct(be.targetROA, 0)}
                 sub={isAr ? `ميزانية الخسارة المسموح بها ${pct(be.allowableLoss, 1)}`
                            : `Allowable loss budget ${pct(be.allowableLoss, 1)}`}
                 status={String(be.vsDownside).replace('✓ ', '')} tone="success"/>
      </div>
    </ChartCard>
    </div>
  );
}

function BeBlock({ title, main, sub, status, tone }) {
  return (
    <div style={{
      padding: 14, borderRadius: 12,
      border: '1px solid var(--mal-line)', background: 'var(--mal-surface-2)',
    }}>
      <div style={{ fontSize: 10.5, fontWeight: 600, letterSpacing: '.06em',
                    textTransform: 'uppercase', color: 'var(--mal-mid-2)', marginBottom: 4 }}>{title}</div>
      <div style={{ fontFamily: 'var(--mal-font-display)', fontStyle: 'italic',
                    fontSize: 26, lineHeight: 1, color: 'var(--mal-ink)' }}>{main}</div>
      <div style={{ fontSize: 11, color: 'var(--mal-mid)', marginTop: 6, lineHeight: 1.5 }}>{sub}</div>
      {status && (
        <div style={{ fontSize: 11, fontWeight: 600, marginTop: 8,
                      color: tone === 'success' ? 'var(--mal-success)' : 'var(--mal-danger)' }}>
          ✓ {status}
        </div>
      )}
    </div>
  );
}

// ============================================================
// Sensitivity heatmap (PD × COF)
// ============================================================
function SensitivitySection({ data, isAr }) {
  const s = data.sensitivity;
  if (!s.grid.length) return null;
  const flat = s.grid.flat();
  const min = Math.min(...flat), max = Math.max(...flat);
  const cellColor = (v) => {
    const t = max === min ? 0.5 : (v - min) / (max - min);
    return v < 0 ? `rgba(214,80,78,${0.15 + 0.55 * (1 - t)})` : `rgba(126,199,159,${0.15 + 0.65 * t})`;
  };
  const baseI = s.cofLevels.indexOf(6.5);
  const baseJ = s.pdMultipliers.indexOf(1.0);
  return (
    <div data-tour-id="econ-sensitivity">
    <ChartCard title={isAr ? 'حساسية المساهمة الصافية · Y3' : 'Sensitivity · Y3 net contribution (AED M)'}
               sub={isAr ? 'الصفوف: تكلفة التمويل · الأعمدة: مضاعف PD' : 'Rows: COF · Cols: PD multiplier'}>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'separate', borderSpacing: 4, fontFamily: 'var(--mal-font-mono)', fontSize: 12 }}>
          <thead>
            <tr>
              <th style={{ padding: 6, color: 'var(--mal-mid)', fontSize: 11 }}/>
              {s.pdMultipliers.map((p, i) => (
                <th key={i} style={{ padding: 6, color: 'var(--mal-mid)', fontSize: 11, textAlign: 'center' }}>
                  {p.toFixed(1)}× PD
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {s.grid.map((row, ri) => (
              <tr key={ri}>
                <td style={{ padding: 6, color: 'var(--mal-mid)', fontSize: 11, fontWeight: 500, textAlign: 'end' }}>
                  COF {s.cofLevels[ri].toFixed(1)}%
                </td>
                {row.map((v, ci) => (
                  <td key={ci} style={{
                    width: 78, textAlign: 'center', padding: '8px 6px',
                    background: cellColor(v),
                    border: ri === baseI && ci === baseJ ? '2px solid var(--mal-primary)' : '1px solid var(--mal-line-2)',
                    borderRadius: 6, color: 'var(--mal-ink)',
                  }}>{v.toFixed(0)}M</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </ChartCard>
    </div>
  );
}

// ============================================================
// Sticky lever panel — always-visible assumption inventory
// ============================================================
function StickyLeverPanel({ data, isMobile, isAr }) {
  const [openGroups, setOpenGroups] = fS({
    volume: true, mix: true, tenor: false, pricing: true, risk: true,
    cost: true, capital: true, opex: false,
  });
  const toggle = (k) => setOpenGroups((o) => ({ ...o, [k]: !o[k] }));
  const i = data.inputs;
  const r = data.risk;

  const total = 31; // count of distinct levers shown below

  return (
    <div data-tour-id="econ-levers" style={{
      position: isMobile ? 'static' : 'sticky', top: 70, alignSelf: 'flex-start',
      background: 'var(--mal-paper)', border: '1px solid var(--mal-line)',
      borderRadius: 'var(--mal-r-lg)',
      maxHeight: isMobile ? 'none' : 'calc(100vh - 90px)',
      overflowY: 'auto',
      padding: 16,
    }}>
      <div style={{ marginBottom: 14 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 }}>
          <div style={{ fontFamily: 'var(--mal-font-display)', fontStyle: 'italic',
                        fontSize: 18, color: 'var(--mal-ink)' }}>
            {isAr ? 'الروافع' : 'Levers'}
          </div>
          <div style={{ fontSize: 10.5, color: 'var(--mal-mid-2)' }}>
            {total} {isAr ? 'رافعة' : 'inputs'}
          </div>
        </div>
        <div style={{ fontSize: 10.5, color: 'var(--mal-mid)', lineHeight: 1.5 }}>
          {isAr
            ? 'للقراءة فقط · المصدر إكسل · مزامنة عند الحفظ'
            : 'Read-only · canonical source is Excel · re-sync after edits'}
        </div>
      </div>

      <LeverGroup name={isAr ? 'الحجم والنمو' : 'Volume & growth'}
                  open={openGroups.volume} onToggle={() => toggle('volume')}
                  items={[
                    ['Disb. Y1', i.disb_y1, 'AED M'],
                    ['Disb. Y2', i.disb_y2, 'AED M'],
                    ['Disb. Y3', i.disb_y3, 'AED M'],
                    ['Disb. Y4', i.disb_y4, 'AED M'],
                    ['Disb. Y5', i.disb_y5, 'AED M'],
                    ['Avg ticket', i.avg_ticket_k, 'AED K'],
                  ]}/>

      <LeverGroup name={isAr ? 'الخليط' : 'Plan mix'}
                  open={openGroups.mix} onToggle={() => toggle('mix')}
                  items={[
                    ['Pay-30 share', i.mix_pay30, '%'],
                    ['BNPL share', i.mix_bnpl, '%'],
                    ['Extension share', i.mix_ext, '%'],
                  ]}/>

      <LeverGroup name={isAr ? 'المدد' : 'Tenor'}
                  open={openGroups.tenor} onToggle={() => toggle('tenor')}
                  items={[
                    ['Pay-30', i.tenor_pay30, 'days'],
                    ['BNPL', i.tenor_bnpl, 'days'],
                    ['Extension', i.tenor_ext, 'days'],
                  ]}/>

      <LeverGroup name={isAr ? 'التسعير والرسوم' : 'Pricing & fees'} hot tourId="econ-levers-pricing"
                  open={openGroups.pricing} onToggle={() => toggle('pricing')}
                  items={[
                    ['Pay-30 fee', i.fee_pay30_mo, '%/mo'],
                    ['BNPL fee', i.fee_bnpl_mo, '%/mo'],
                    ['Extension APR', i.fee_ext_apr, '%'],
                    ['Advance rate', i.advance_rate, '% of invoice'],
                  ]}/>

      <LeverGroup name={isAr ? 'تكلفة التمويل' : 'Cost of funds'}
                  open={openGroups.cost} onToggle={() => toggle('cost')}
                  items={[
                    ['Cost of funds', i.cof_apr, '% APR'],
                  ]}/>

      <LeverGroup name={isAr ? 'المخاطر · PD/LGD' : 'Risk · PD / LGD / EAD'} hot tourId="econ-levers-risk"
                  open={openGroups.risk} onToggle={() => toggle('risk')}
                  items={[
                    ['Pay-30 PD', r.pay30.pd, '% p.a.'],
                    ['BNPL PD', r.bnpl.pd, '% p.a.'],
                    ['Extension PD', r.ext.pd, '% p.a.'],
                    ['Pay-30 LGD', r.pay30.lgd, '%'],
                    ['BNPL LGD', r.bnpl.lgd, '%'],
                    ['Extension LGD', r.ext.lgd, '%'],
                    ['EAD (all tracks)', r.pay30.ead, '%'],
                  ]}/>

      <LeverGroup name={isAr ? 'التشغيل' : 'OpEx (% of book)'}
                  open={openGroups.opex} onToggle={() => toggle('opex')}
                  items={[
                    ['OpEx mature', i.opex_pct, '% of book'],
                    ['Y1 multiplier', i.opex_y1_mult, 'x'],
                    ['Y2 multiplier', i.opex_y2_mult, 'x'],
                    ['Y3 multiplier', i.opex_y3_mult, 'x'],
                    ['Y4 multiplier', i.opex_y4_mult, 'x'],
                    ['Y5 multiplier', i.opex_y5_mult, 'x'],
                  ]}/>

      <LeverGroup name={isAr ? 'رأس المال' : 'Capital'}
                  open={openGroups.capital} onToggle={() => toggle('capital')}
                  items={[
                    ['Equity', i.equity_pct, '% of book'],
                  ]}/>

      {/* Hint footer */}
      <div style={{
        marginTop: 12, padding: 10, borderRadius: 10,
        background: 'var(--mal-surface-2)', border: '1px solid var(--mal-line-2)',
        fontSize: 10.5, color: 'var(--mal-mid)', lineHeight: 1.55,
      }}>
        {isAr
          ? 'لتعديل قيمة، افتح إكسل وحدّث ورقة Inputs أو Risk، ثم شغّل sync_p1_to_jsx.py.'
          : 'To change a value, edit Inputs or Risk sheet in Excel, then run sync_p1_to_jsx.py.'}
      </div>
    </div>
  );
}

function LeverGroup({ name, items, open, onToggle, hot, tourId }) {
  return (
    <div data-tour-id={tourId} style={{ borderTop: '1px solid var(--mal-line-2)', paddingTop: 10, marginTop: 10 }}>
      <button onClick={onToggle} style={{
        all: 'unset', cursor: 'pointer', width: '100%',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <span style={{
          fontSize: 10.5, fontWeight: 700, letterSpacing: '.08em',
          textTransform: 'uppercase',
          color: hot ? 'var(--mal-primary)' : 'var(--mal-ink)',
          display: 'inline-flex', alignItems: 'center', gap: 6,
        }}>
          {hot && <span style={{
            width: 5, height: 5, borderRadius: 999, background: 'var(--mal-primary)',
          }}/>}
          {name}
        </span>
        <span style={{
          fontSize: 13, color: 'var(--mal-mid)',
          transform: open ? 'rotate(180deg)' : 'rotate(0)',
          transition: 'transform .15s',
        }}>▾</span>
      </button>
      {open && (
        <div style={{ marginTop: 8 }}>
          {items.map(([label, val, unit], i) => (
            <div key={i} style={{
              display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
              padding: '5px 0', fontSize: 12,
              borderBottom: i < items.length - 1 ? '1px dashed var(--mal-line-2)' : 'none',
            }}>
              <span style={{ color: 'var(--mal-mid)' }}>{label}</span>
              <span style={{ fontFamily: 'var(--mal-font-mono)', color: 'var(--mal-ink)', fontWeight: 600 }}>
                {typeof val === 'number' ? val.toLocaleString(undefined, { maximumFractionDigits: 2 }) : val}
                <span style={{ color: 'var(--mal-mid-2)', fontWeight: 400, marginInlineStart: 4 }}>{unit}</span>
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ============================================================
// Sync footer — CSV export + last-updated meta
// ============================================================
function SyncFooter({ data, exportCsv, isAr }) {
  return (
    <div data-tour-id="econ-sync" style={{
      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      flexWrap: 'wrap', gap: 12,
      padding: '14px 18px', borderRadius: 12,
      background: 'var(--mal-paper)', border: '1px solid var(--mal-line)',
    }}>
      <div style={{ fontSize: 11.5, color: 'var(--mal-mid)', lineHeight: 1.6 }}>
        <strong style={{ color: 'var(--mal-ink)' }}>{isAr ? 'مصدر الحقيقة' : 'Source of truth'}:</strong> {data.meta.workbook}
        <span style={{ marginInline: 8, color: 'var(--mal-mid-2)' }}>·</span>
        {data.meta.sheets} {isAr ? 'ورقة' : 'sheets'}
        <span style={{ marginInline: 8, color: 'var(--mal-mid-2)' }}>·</span>
        {isAr ? 'مزامنة' : 'synced'} {data.meta.lastUpdated}
      </div>
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        <a href={`models/${data.meta.workbook}`} download={data.meta.workbook}
           style={{
             display: 'inline-flex', alignItems: 'center', gap: 6,
             padding: '8px 14px', background: 'var(--mal-ink)', color: '#FAF7EE',
             borderRadius: 999, fontSize: 12, fontWeight: 500,
             textDecoration: 'none', cursor: 'pointer',
           }}>
          ↓ {isAr ? 'تحميل ملف الإكسل الكامل' : 'Download full Excel workbook'}
        </a>
        <button onClick={exportCsv} style={{
          all: 'unset', cursor: 'pointer',
          padding: '8px 14px', background: 'transparent', color: 'var(--mal-ink)',
          border: '1px solid var(--mal-line)',
          borderRadius: 999, fontSize: 12, fontWeight: 500,
        }}>↓ {isAr ? 'CSV' : 'CSV (P&L only)'}</button>
      </div>
    </div>
  );
}

// ============================================================
// VintageLossSvg — bespoke 3-line chart, all keys explicit
// ============================================================
function VintageLossSvg({ vintage }) {
  const months = vintage.lossCurve.months;
  const series = [
    { id: 'y3', label: 'Y3 cohort', values: vintage.lossCurveAED.y3, color: 'var(--mal-primary)' },
    { id: 'y2', label: 'Y2 cohort', values: vintage.lossCurveAED.y2, color: 'var(--mal-primary-3)' },
    { id: 'y1', label: 'Y1 cohort', values: vintage.lossCurveAED.y1, color: 'var(--mal-iri-2)' },
  ];
  const allVals = series.flatMap((s) => s.values);
  const maxV = Math.max(...allVals, 1);
  const W = 480, H = 220, padTop = 16, padBottom = 28, padX = 30;
  const innerW = W - padX * 2, innerH = H - padTop - padBottom;
  const xAt = (i) => padX + (i / (months.length - 1 || 1)) * innerW;
  const yAt = (v) => padTop + (1 - v / maxV) * innerH;
  return (
    <div>
      <svg viewBox={`0 0 ${W} ${H}`} style={{ width: '100%', height: H, display: 'block' }} role="img" aria-label="vintage loss curves">
        {[0, 0.5, 1].map((p) => (
          <line key={'grid-' + p}
                x1={padX} y1={padTop + p * innerH}
                x2={W - padX} y2={padTop + p * innerH}
                stroke="var(--mal-line)" strokeDasharray="2 4" strokeWidth="1"/>
        ))}
        {months.map((m, i) => i % 4 === 0 ? (
          <text key={'tick-' + i} x={xAt(i)} y={H - padBottom + 16} textAnchor="middle"
                fontSize="10" fill="var(--mal-mid)">{m}</text>
        ) : null)}
        {series.map((s) => {
          const points = s.values.map((v, i) => `${xAt(i)},${yAt(v)}`).join(' ');
          return (
            <polyline key={'line-' + s.id} points={points} fill="none"
                      stroke={s.color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          );
        })}
      </svg>
      <div style={{ display: 'flex', gap: 14, justifyContent: 'center', marginTop: 8, fontSize: 11 }}>
        {series.map((s) => (
          <span key={'leg-' + s.id} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <span style={{ width: 10, height: 3, background: s.color, borderRadius: 2, display: 'inline-block' }}/>
            <span style={{ color: 'var(--mal-mid)' }}>
              {s.label} · {(s.values[s.values.length - 1] || 0).toFixed(1)}M
            </span>
          </span>
        ))}
      </div>
    </div>
  );
}

// ============================================================
// Generic ChartCard
// ============================================================
function ChartCard({ title, sub, children }) {
  return (
    <div className="mal-fade-up" style={{
      background: 'var(--mal-paper)', border: '1px solid var(--mal-line)',
      borderRadius: 'var(--mal-r-lg)', padding: 18,
    }}>
      <div style={{ marginBottom: 12 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--mal-ink)' }}>{title}</div>
        {sub && <div style={{ fontSize: 11, color: 'var(--mal-mid)', marginTop: 2 }}>{sub}</div>}
      </div>
      {children}
    </div>
  );
}

// ============================================================
// Cell-style helpers
// ============================================================
function th({ first = false } = {}) {
  return {
    textAlign: first ? 'start' : 'end',
    padding: '8px 10px', fontSize: 11,
    textTransform: 'uppercase', letterSpacing: '.06em',
    color: 'var(--mal-mid)',
    borderBottom: '2px solid var(--mal-line)',
  };
}
function td({ label = false, sub = false, negative = false, tone, role } = {}) {
  const colors = {
    success: 'var(--mal-success)', danger: 'var(--mal-danger)', muted: 'var(--mal-mid-2)',
  };
  return {
    padding: '8px 10px', textAlign: label ? 'start' : 'end',
    borderBottom: '1px solid var(--mal-line-2)',
    color: tone ? colors[tone] : (negative ? 'var(--mal-danger)' : (label ? 'var(--mal-mid)' : 'var(--mal-ink)')),
    fontFamily: label ? 'inherit' : 'var(--mal-font-mono)',
    paddingInlineStart: sub ? 22 : (label ? 10 : undefined),
    fontWeight: role === 'header' ? 600 : undefined,
  };
}

// ============================================================
// Expose to global
// ============================================================
window.SectionFinancial = SectionFinancial;
